// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A10_RegistroEvolucaoEnfermagem")]
    public partial class A10RegistroEvolucaoEnfermagem
    {
        public A10RegistroEvolucaoEnfermagem()
        {
            RelHistoricoEvolucaoEnfermagem = new HashSet<RelHistoricoEvolucaoEnfermagem>();
        }

        [Key]
        [Column("A10_RegistroEvolucaoEnfermagem_ID")]
        public int A10RegistroEvolucaoEnfermagemId { get; set; }
        [Required]
        [Column("A13_Profissional_CodigoSus")]
        [StringLength(350)]
        public string A13ProfissionalCodigoSus { get; set; }
        [Column("A10_RegistroEvolucaoEnfermagem_Data", TypeName = "date")]
        public DateTime? A10RegistroEvolucaoEnfermagemData { get; set; }
        [Column("A10_RegistroEvolucaoEnfermagem_Hora", TypeName = "time(0)")]
        public TimeSpan? A10RegistroEvolucaoEnfermagemHora { get; set; }
        [Column("A10_RegistroEvolucaoEnfermagem_Descrição")]
        [StringLength(999)]
        public string A10RegistroEvolucaoEnfermagemDescrição { get; set; }

        [ForeignKey(nameof(A13ProfissionalCodigoSus))]
        [InverseProperty(nameof(A13Profissional.A10RegistroEvolucaoEnfermagem))]
        public virtual A13Profissional A13ProfissionalCodigoSusNavigation { get; set; }
        [InverseProperty("A10RegistroEvolucaoEnfermagem")]
        public virtual ICollection<RelHistoricoEvolucaoEnfermagem> RelHistoricoEvolucaoEnfermagem { get; set; }
    }
}