// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A11_RegistroEvolucaoMedicaDiaria")]
    public partial class A11RegistroEvolucaoMedicaDiaria
    {
        public A11RegistroEvolucaoMedicaDiaria()
        {
            RelHistoricoEvolucaoMedicaDiaria = new HashSet<RelHistoricoEvolucaoMedicaDiaria>();
        }

        [Key]
        [Column("A11_RegistroEvolucaoMedicaDiaria_ID")]
        public int A11RegistroEvolucaoMedicaDiariaId { get; set; }
        [Required]
        [Column("A13_Profissional_CodigoSus")]
        [StringLength(350)]
        public string A13ProfissionalCodigoSus { get; set; }
        [Column("A11_RegistroEvolucaoMedicaDiaria_Data", TypeName = "date")]
        public DateTime? A11RegistroEvolucaoMedicaDiariaData { get; set; }
        [Column("A11_RegistroEvolucaoMedicaDiaria_Hora", TypeName = "time(0)")]
        public TimeSpan? A11RegistroEvolucaoMedicaDiariaHora { get; set; }
        [Column("A11_RegistroEvolucaoMedicaDiaria_Descricao")]
        [StringLength(999)]
        public string A11RegistroEvolucaoMedicaDiariaDescricao { get; set; }

        [ForeignKey(nameof(A13ProfissionalCodigoSus))]
        [InverseProperty(nameof(A13Profissional.A11RegistroEvolucaoMedicaDiaria))]
        public virtual A13Profissional A13ProfissionalCodigoSusNavigation { get; set; }
        [InverseProperty("A11RegistroEvolucaoMedicaDiaria")]
        public virtual ICollection<RelHistoricoEvolucaoMedicaDiaria> RelHistoricoEvolucaoMedicaDiaria { get; set; }
    }
}