// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A12_Ocupacao")]
    public partial class A12Ocupacao
    {
        public A12Ocupacao()
        {
            A22Agenda = new HashSet<A22Agenda>();
            RelProfissionalOcupacao = new HashSet<RelProfissionalOcupacao>();
        }

        [Key]
        [Column("A12_Ocupacao_Codigo")]
        [StringLength(250)]
        public string A12OcupacaoCodigo { get; set; }
        [Column("A12_Ocupacao_Descricao")]
        [StringLength(500)]
        public string A12OcupacaoDescricao { get; set; }

        [InverseProperty("A12OcupacaoCodigoNavigation")]
        public virtual ICollection<A22Agenda> A22Agenda { get; set; }
        [InverseProperty("A12OcupacaoCodigoNavigation")]
        public virtual ICollection<RelProfissionalOcupacao> RelProfissionalOcupacao { get; set; }
    }
}