// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TCC.GestaoSaude.Common;

namespace TCC.GestaoSaude.Models
{
    [Table("A15_CargaHorariaProfissional")]
    public partial class A15CargaHorariaProfissional
    {
        [Key]
        [Column("A15_CargaHorariaProfissional_ID")]
        public int A15CargaHorariaProfissionalId { get; set; }
        [Required]
        [Column("A13_Profissional_CodigoCNS")]
        [StringLength(350)]
        public string A13ProfissionalCodigoCns { get; set; }
        [Column("A15_CargaHorariaProfissional_QtCargaHorariaAmbulatorial")]
        public int A15CargaHorariaProfissionalQtCargaHorariaAmbulatorial { get; set; }
        [Column("A15_Data", TypeName = "datetime2(0)")]
        public DateTime? A15Data { get; set; }

        [ForeignKey(nameof(A13ProfissionalCodigoCns))]
        [InverseProperty(nameof(A13Profissional.A15CargaHorariaProfissional))]
        public virtual A13Profissional A13ProfissionalCodigoCnsNavigation { get; set; }

        [NotMapped]
        public List<Mensagem> Mensagens { get; set; }
    }
}