// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A1_Usuario")]
    public partial class A1Usuario
    {
        public A1Usuario()
        {
            A3InformacaoCadastro = new HashSet<A3InformacaoCadastro>();
            RelUsuarioPerfil = new HashSet<RelUsuarioPerfil>();
        }

        [Key]
        [Column("A1_Usuario_ID")]
        public int A1UsuarioId { get; set; }
        [Required]
        [Column("A1_Usuario_NumeroCPF")]
        [StringLength(20)]
        public string A1UsuarioNumeroCpf { get; set; }
        [Column("A1_Usuario_Nome")]
        [StringLength(100)]
        public string A1UsuarioNome { get; set; }
        [Column("A1_Usuario_Senha")]
        [StringLength(20)]
        public string A1UsuarioSenha { get; set; }

        [InverseProperty("A1Usuario")]
        public virtual ICollection<A3InformacaoCadastro> A3InformacaoCadastro { get; set; }
        [InverseProperty("A1Usuario")]
        public virtual ICollection<RelUsuarioPerfil> RelUsuarioPerfil { get; set; }
    }
}