// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A20_TipoEstabelecimento")]
    public partial class A20TipoEstabelecimento
    {
        public A20TipoEstabelecimento()
        {
            A21Estabelecimento = new HashSet<A21Estabelecimento>();
        }

        [Key]
        [Column("A20_TipoEstabelecimento_ID")]
        public int A20TipoEstabelecimentoId { get; set; }
        [Column("A20_TipoEstabelecimento_Codigo")]
        [StringLength(200)]
        public string A20TipoEstabelecimentoCodigo { get; set; }
        [Column("A20_TipoEstabelecimento_Descricao")]
        [StringLength(450)]
        public string A20TipoEstabelecimentoDescricao { get; set; }

        [InverseProperty("A20TipoEstabelecimento")]
        public virtual ICollection<A21Estabelecimento> A21Estabelecimento { get; set; }
    }
}