// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A21_Estabelecimento")]
    public partial class A21Estabelecimento
    {
        public A21Estabelecimento()
        {
            RelEstabelecimentoLeito = new HashSet<RelEstabelecimentoLeito>();
            RelProfissionalOcupacao = new HashSet<RelProfissionalOcupacao>();
        }

        [Key]
        [Column("A21_Estabelecimento_ID")]
        public int A21EstabelecimentoId { get; set; }
        [Column("A20_TipoEstabelecimento_ID")]
        public int A20TipoEstabelecimentoId { get; set; }
        [Column("A21_Estabelecimento_CodigoUnidade")]
        [StringLength(100)]
        public string A21EstabelecimentoCodigoUnidade { get; set; }
        [Column("A21_Estabelecimento_CodigoEstabelecimento")]
        [StringLength(100)]
        public string A21EstabelecimentoCodigoEstabelecimento { get; set; }
        [Column("A21_Estabelecimento_CNPJ")]
        [StringLength(30)]
        public string A21EstabelecimentoCnpj { get; set; }
        [Column("A21_Estabelecimento_RazaoSocial")]
        [StringLength(150)]
        public string A21EstabelecimentoRazaoSocial { get; set; }
        [Column("A21_Estabelecimento_NomeFantasia")]
        [StringLength(150)]
        public string A21EstabelecimentoNomeFantasia { get; set; }
        [Column("A21_Estabelecimento_Logradouro")]
        [StringLength(150)]
        public string A21EstabelecimentoLogradouro { get; set; }
        [Column("A21_Estabelecimento_Endereco")]
        [StringLength(150)]
        public string A21EstabelecimentoEndereco { get; set; }
        [Column("A21_Estabelecimento_Numero")]
        [StringLength(10)]
        public string A21EstabelecimentoNumero { get; set; }
        [Column("A21_Estabelecimento_Complemento")]
        [StringLength(150)]
        public string A21EstabelecimentoComplemento { get; set; }
        [Column("A21_Estabelecimento_Bairro")]
        [StringLength(100)]
        public string A21EstabelecimentoBairro { get; set; }
        [Column("A21_Estabelecimento_Cep")]
        [StringLength(20)]
        public string A21EstabelecimentoCep { get; set; }
        [Column("A21_Estabelecimento_Telefone")]
        [StringLength(15)]
        public string A21EstabelecimentoTelefone { get; set; }
        [Column("A21_Estabelecimento_Fax")]
        [StringLength(15)]
        public string A21EstabelecimentoFax { get; set; }
        [Column("A21_Estabelecimento_Email")]
        [StringLength(150)]
        public string A21EstabelecimentoEmail { get; set; }
        [Column("A21_Estabelecimento_Latitude")]
        [StringLength(150)]
        public string A21EstabelecimentoLatitude { get; set; }
        [Column("A21_Estabelecimento_Longitude")]
        [StringLength(150)]
        public string A21EstabelecimentoLongitude { get; set; }
        [Column("A21_Estabelecimento_DataAtualizacaoGeografica", TypeName = "datetime2(0)")]
        public DateTime? A21EstabelecimentoDataAtualizacaoGeografica { get; set; }
        [Column("A21_Estabelecimento_DataAtualizacao", TypeName = "datetime2(0)")]
        public DateTime? A21EstabelecimentoDataAtualizacao { get; set; }
        [Column("A21_Estabelecimento_DataAtualizacaoOrigem", TypeName = "datetime2(0)")]
        public DateTime? A21EstabelecimentoDataAtualizacaoOrigem { get; set; }

        [ForeignKey(nameof(A20TipoEstabelecimentoId))]
        [InverseProperty("A21Estabelecimento")]
        public virtual A20TipoEstabelecimento A20TipoEstabelecimento { get; set; }
        [InverseProperty("A21Estabelecimento")]
        public virtual ICollection<RelEstabelecimentoLeito> RelEstabelecimentoLeito { get; set; }
        [InverseProperty("A21Estabelecimento")]
        public virtual ICollection<RelProfissionalOcupacao> RelProfissionalOcupacao { get; set; }
    }
}