// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A23_TipoAgenda")]
    public partial class A23TipoAgenda
    {
        public A23TipoAgenda()
        {
            A22Agenda = new HashSet<A22Agenda>();
        }

        [Key]
        [Column("A23_TipoAgenda_ID")]
        public int A23TipoAgendaId { get; set; }
        [Column("A23_TipoAgenda_Descricao")]
        [StringLength(50)]
        public string A23TipoAgendaDescricao { get; set; }

        [InverseProperty("A23TipoAgenda")]
        public virtual ICollection<A22Agenda> A22Agenda { get; set; }
    }
}