// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A26_Leito")]
    public partial class A26Leito
    {
        public A26Leito()
        {
            RelEstabelecimentoLeito = new HashSet<RelEstabelecimentoLeito>();
        }

        [Key]
        [Column("A26_Leito_ID")]
        public int A26LeitoId { get; set; }
        [Column("A26_Leito_CodigoLeito")]
        public int? A26LeitoCodigoLeito { get; set; }
        [Column("A26_Leito_Descricao")]
        [StringLength(250)]
        public string A26LeitoDescricao { get; set; }
        [Column("A26_Leito_TipoLeito")]
        public int? A26LeitoTipoLeito { get; set; }

        [InverseProperty("A26Leito")]
        public virtual ICollection<RelEstabelecimentoLeito> RelEstabelecimentoLeito { get; set; }
    }
}