// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TCC.GestaoSaude.Common;

namespace TCC.GestaoSaude.Models
{
    [Table("A28_CodigoInternacionalDoenca")]
    public partial class A28CodigoInternacionalDoenca
    {
        [Key]
        [Column("A28_CodigoInternacionalDoenca_ID")]
        public int A28CodigoInternacionalDoencaId { get; set; }
        [Column("A28_CodigoInternacionalDoenca_Codigo")]
        [StringLength(20)]
        public string A28CodigoInternacionalDoencaCodigo { get; set; }
        [Column("A28_CodigoInternacionalDoenca_Valor")]
        [StringLength(150)]
        public string A28CodigoInternacionalDoencaValor { get; set; }

        [NotMapped]
        public List<Mensagem> Mensagens { get; set; }
    }
}