// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TCC.GestaoSaude.Common;

namespace TCC.GestaoSaude.Models
{
    [Table("A29_Atendimento")]
    public partial class A29Atendimento
    {
        public A29Atendimento()
        {
            RelAtendimentoProntuario = new HashSet<RelAtendimentoProntuario>();
            Mensagens = new List<Mensagem>();
        }

        [Key]
        [Column("A29_Atendimento_ID")]
        public int A29AtendimentoId { get; set; }
        [Column("A3_InformacaoCadastro_ID")]
        public int A3InformacaoCadastroId { get; set; }
        [Column("A29_Data", TypeName = "datetime2(0)")]
        public DateTime? A29Data { get; set; }

        [ForeignKey(nameof(A3InformacaoCadastroId))]
        [InverseProperty("A29Atendimento")]
        public virtual A3InformacaoCadastro A3InformacaoCadastro { get; set; }
        [InverseProperty("A29Atendimento")]
        public virtual ICollection<RelAtendimentoProntuario> RelAtendimentoProntuario { get; set; }

        [NotMapped]
        public List<Mensagem> Mensagens { get; set; }
    }
}