// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("A4_CartaoVacinacao")]
    public partial class A4CartaoVacinacao
    {
        public A4CartaoVacinacao()
        {
            A5Vacina = new HashSet<A5Vacina>();
        }

        [Key]
        [Column("A4_CartaoVacinacao_ID")]
        public int A4CartaoVacinacaoId { get; set; }
        [Column("A3_InformacaoCadastro_ID")]
        public int A3InformacaoCadastroId { get; set; }
        [Column("A4_CartaoVacinacao_Data", TypeName = "date")]
        public DateTime? A4CartaoVacinacaoData { get; set; }

        [ForeignKey(nameof(A3InformacaoCadastroId))]
        [InverseProperty("A4CartaoVacinacao")]
        public virtual A3InformacaoCadastro A3InformacaoCadastro { get; set; }
        [InverseProperty("A4CartaoVacinacao")]
        public virtual ICollection<A5Vacina> A5Vacina { get; set; }
    }
}