// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using TCC.GestaoSaude.Common;

namespace TCC.GestaoSaude.Models
{
    [Table("A9_Prontuario")]
    public partial class A9Prontuario
    {
        public A9Prontuario()
        {
            RelAtendimentoProntuario = new HashSet<RelAtendimentoProntuario>();
            RelHistoricoEvolucaoEnfermagem = new HashSet<RelHistoricoEvolucaoEnfermagem>();
            RelHistoricoEvolucaoMedicaDiaria = new HashSet<RelHistoricoEvolucaoMedicaDiaria>();
            RelHistoricoExamePaciente = new HashSet<RelHistoricoExamePaciente>();
            RelProntuarioRecomendacaoMedica = new HashSet<RelProntuarioRecomendacaoMedica>();
            Mensagens = new List<Mensagem>();
        }

        [Key]
        [Column("A9_Prontuario_ID")]
        public int A9ProntuarioId { get; set; }
        [Column("A9_Prontuario_Internado")]
        public bool? A9ProntuarioInternado { get; set; }
        [Column("A9_Prontuario_RaciocinioMedico")]
        [StringLength(999)]
        public string A9ProntuarioRaciocinioMedico { get; set; }
        [Column("A9_Prontuario_HipotesesDiagnostica")]
        [StringLength(999)]
        public string A9ProntuarioHipotesesDiagnostica { get; set; }
        [Column("A9_Prontuario_CondutaTerapeuta")]
        [StringLength(999)]
        public string A9ProntuarioCondutaTerapeuta { get; set; }
        [Column("A9_Prontuario_PrescricaoMedica")]
        [StringLength(999)]
        public string A9ProntuarioPrescricaoMedica { get; set; }
        [Column("A9_Prontuario_DescricaoCirurgica")]
        [StringLength(999)]
        public string A9ProntuarioDescricaoCirurgica { get; set; }
        [Column("A9_Prontuario_DiagnosticoMedico")]
        [StringLength(999)]
        public string A9ProntuarioDiagnosticoMedico { get; set; }

        [InverseProperty("A9Prontuario")]
        public virtual ICollection<RelAtendimentoProntuario> RelAtendimentoProntuario { get; set; }
        [InverseProperty("A9Prontuario")]
        public virtual ICollection<RelHistoricoEvolucaoEnfermagem> RelHistoricoEvolucaoEnfermagem { get; set; }
        [InverseProperty("A9Prontuario")]
        public virtual ICollection<RelHistoricoEvolucaoMedicaDiaria> RelHistoricoEvolucaoMedicaDiaria { get; set; }
        [InverseProperty("A9Prontuario")]
        public virtual ICollection<RelHistoricoExamePaciente> RelHistoricoExamePaciente { get; set; }
        [InverseProperty("A9Prontuario")]
        public virtual ICollection<RelProntuarioRecomendacaoMedica> RelProntuarioRecomendacaoMedica { get; set; }

        [NotMapped]
        public List<Mensagem> Mensagens { get; set; }
    }
}