// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("Rel_AtendimentoProntuario")]
    public partial class RelAtendimentoProntuario
    {
        [Key]
        [Column("A29_Atendimento_ID")]
        public int A29AtendimentoId { get; set; }
        [Key]
        [Column("A9_Prontuario_ID")]
        public int A9ProntuarioId { get; set; }

        [ForeignKey(nameof(A29AtendimentoId))]
        [InverseProperty("RelAtendimentoProntuario")]
        public virtual A29Atendimento A29Atendimento { get; set; }
        [ForeignKey(nameof(A9ProntuarioId))]
        [InverseProperty("RelAtendimentoProntuario")]
        public virtual A9Prontuario A9Prontuario { get; set; }
    }
}