// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("Rel_EstabelecimentoLeito")]
    public partial class RelEstabelecimentoLeito
    {
        [Key]
        [Column("A21_Estabelecimento_ID")]
        public int A21EstabelecimentoId { get; set; }
        [Key]
        [Column("A26_Leito_ID")]
        public int A26LeitoId { get; set; }
        [Column("Rel_EstabelecimentoLeito_QtLeito")]
        public int? RelEstabelecimentoLeitoQtLeito { get; set; }
        [Column("Rel_Estabelecimento_QtLeitoSus")]
        public int? RelEstabelecimentoQtLeitoSus { get; set; }
        [Column("Rel_DataAtualizacao", TypeName = "datetime2(0)")]
        public DateTime? RelDataAtualizacao { get; set; }

        [ForeignKey(nameof(A21EstabelecimentoId))]
        [InverseProperty("RelEstabelecimentoLeito")]
        public virtual A21Estabelecimento A21Estabelecimento { get; set; }
        [ForeignKey(nameof(A26LeitoId))]
        [InverseProperty("RelEstabelecimentoLeito")]
        public virtual A26Leito A26Leito { get; set; }
    }
}