// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("Rel_HistoricoEvolucaoEnfermagem")]
    public partial class RelHistoricoEvolucaoEnfermagem
    {
        [Key]
        [Column("A9_Prontuario_ID")]
        public int A9ProntuarioId { get; set; }
        [Key]
        [Column("A10_RegistroEvolucaoEnfermagem_ID")]
        public int A10RegistroEvolucaoEnfermagemId { get; set; }

        [ForeignKey(nameof(A10RegistroEvolucaoEnfermagemId))]
        [InverseProperty("RelHistoricoEvolucaoEnfermagem")]
        public virtual A10RegistroEvolucaoEnfermagem A10RegistroEvolucaoEnfermagem { get; set; }
        [ForeignKey(nameof(A9ProntuarioId))]
        [InverseProperty("RelHistoricoEvolucaoEnfermagem")]
        public virtual A9Prontuario A9Prontuario { get; set; }
    }
}