// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("Rel_HistoricoExamePaciente")]
    public partial class RelHistoricoExamePaciente
    {
        [Key]
        [Column("A9_Prontuario_ID")]
        public int A9ProntuarioId { get; set; }
        [Key]
        [Column("A18_ProcedimentoExame_ID")]
        public int A18ProcedimentoExameId { get; set; }
        [Column("Rel_Imagem")]
        public byte[] RelImagem { get; set; }

        [ForeignKey(nameof(A18ProcedimentoExameId))]
        [InverseProperty("RelHistoricoExamePaciente")]
        public virtual A18ProcedimentoExame A18ProcedimentoExame { get; set; }
        [ForeignKey(nameof(A9ProntuarioId))]
        [InverseProperty("RelHistoricoExamePaciente")]
        public virtual A9Prontuario A9Prontuario { get; set; }
    }
}