// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    [Table("Rel_ProntuarioRecomendacaoMedica")]
    public partial class RelProntuarioRecomendacaoMedica
    {
        [Key]
        [Column("A9_Prontuario_ID")]
        public int A9ProntuarioId { get; set; }
        [Key]
        [Column("A24_RecomendacaoMedica_ID")]
        public int A24RecomendacaoMedicaId { get; set; }

        [ForeignKey(nameof(A24RecomendacaoMedicaId))]
        [InverseProperty("RelProntuarioRecomendacaoMedica")]
        public virtual A24RecomendacaoMedica A24RecomendacaoMedica { get; set; }
        [ForeignKey(nameof(A9ProntuarioId))]
        [InverseProperty("RelProntuarioRecomendacaoMedica")]
        public virtual A9Prontuario A9Prontuario { get; set; }
    }
}