// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TCC.GestaoSaude.Models
{
    public partial class RelUsuarioInternoProfissional
    {
        [Key]
        [Column("A2_UsuarioInterno_ID")]
        public int A2UsuarioInternoId { get; set; }
        [Key]
        [Column("A13_Profissional_CodigoCNS")]
        [StringLength(350)]
        public string A13ProfissionalCodigoCns { get; set; }

        [ForeignKey(nameof(A13ProfissionalCodigoCns))]
        [InverseProperty(nameof(A13Profissional.RelUsuarioInternoProfissional))]
        public virtual A13Profissional A13ProfissionalCodigoCnsNavigation { get; set; }
        [ForeignKey(nameof(A2UsuarioInternoId))]
        [InverseProperty("RelUsuarioInternoProfissional")]
        public virtual A2UsuarioInterno A2UsuarioInterno { get; set; }
    }
}